language: node_js

node_js:
  - "8.0"

script:
  - echo "Deploy for deveop"

install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy  --project joyful-tama-dev --token $FIREBASE_TOKEN

